hpc_temp <- read.csv("household_power_consumption.txt", header = TRUE, sep = ";", na.strings = "?")
hpc_temp$DateTime <- strptime(paste(hpc_temp$Date,hpc_temp$Time), "%d/%m/%Y %H:%M:%S")
hpc_temp$Date <- as.Date(hpc_temp$Date, "%d/%m/%Y")
hpc <- subset(hpc_temp, hpc_temp$Date %in% c(as.Date("2007-02-01"), as.Date("2007-02-02")))
rm(hpc_temp)
hpc$Weekday <- weekdays(hpc$Date)
png(filename = "Project1_Plot1.png", width = 480, height = 480)
hist(hpc$Global_active_power, col = "Red", main = "Global Active Power", xlab = "Global Active Power (kilowatts)")
dev.off()
